AllCops:
  RunRailsCops: true

  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'Procfile'
    - 'bin/*'
    - 'vendor/*'

Documentation:
  Enabled: false
